name: "DevSecOps Security Gates"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  iac-security:
    name: "Infrastructure Security Scan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Checkov (IaC Scan)
        uses: bridgecrewio/checkov-action@master
        with:
          directory: infrastructure/terraform
          framework: terraform
          soft_fail: false # El pipeline falla si hay riesgos cr√≠ticos

  app-security:
    name: "Application & Container Scan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Trivy (Filesystem Scan)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          exit-code: '1' # Falla si encuentra vulnerabilidades
          severity: 'CRITICAL,HIGH'